In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
import csv

In [2]:
#define data to pull from WHO GHO API
url= "https://ghoapi.azureedge.net/api/SA_0000001476"
url1= "https://ghoapi.azureedge.net/api/SA_0000001398"
url2= "https://ghoapi.azureedge.net/api/SA_0000001732"
url3= "https://ghoapi.azureedge.net/api/SA_0000001523"
url4= "https://ghoapi.azureedge.net/api/WHOSIS_000002"


# list to store URLS 
urls= [url,url1,url2,url3,url4]

# Dictionary to store dataframes
dataframes = {}

In [3]:
# Fetch data from each URL and create dataframes
for idx, url in enumerate(urls):
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        df_name = f"df_{idx}"  # Name the dataframe
        dataframes[df_name] = pd.DataFrame(data)
        print("Data from", url, "has been fetched and stored in", df_name)
    else:
        print("Failed to fetch data from", url)

Data from https://ghoapi.azureedge.net/api/SA_0000001476 has been fetched and stored in df_0
Data from https://ghoapi.azureedge.net/api/SA_0000001398 has been fetched and stored in df_1
Data from https://ghoapi.azureedge.net/api/SA_0000001732 has been fetched and stored in df_2
Data from https://ghoapi.azureedge.net/api/SA_0000001523 has been fetched and stored in df_3
Data from https://ghoapi.azureedge.net/api/WHOSIS_000002 has been fetched and stored in df_4

In [4]:
# Create variables for each DataFrame
for df_name, df in dataframes.items():
    globals()[df_name] = df

# Test the created dataframes and write each dataframe to CSV
for df_name, df in dataframes.items():
    print("DataFrame:", df_name)
    print(df)
    print()


# Write dataframe to CSV
    csv_filename = f"{df_name}.csv"
    df.to_csv(csv_filename, index=False)
    print(f"DataFrame '{df_name}' has been written to '{csv_filename}' CSV file.")
    print()

DataFrame: df_0
                                        @odata.context  \
0    https://ghoapi.azureedge.net/api/$metadata#SA_...
1    https://ghoapi.azureedge.net/api/$metadata#SA_...
2    https://ghoapi.azureedge.net/api/$metadata#SA_...
3    https://ghoapi.azureedge.net/api/$metadata#SA_...
4    https://ghoapi.azureedge.net/api/$metadata#SA_...
..                                                 ...
500  https://ghoapi.azureedge.net/api/$metadata#SA_...
501  https://ghoapi.azureedge.net/api/$metadata#SA_...
502  https://ghoapi.azureedge.net/api/$metadata#SA_...
503  https://ghoapi.azureedge.net/api/$metadata#SA_...
504  https://ghoapi.azureedge.net/api/$metadata#SA_...

                                                 value
0    {'Id': 4548508, 'IndicatorCode': 'SA_000000147...
1    {'Id': 4539127, 'IndicatorCode': 'SA_000000147...
2    {'Id': 4539079, 'IndicatorCode': 'SA_000000147...
3    {'Id': 4539550, 'IndicatorCode': 'SA_000000147...
4    {'Id': 4519729, 'IndicatorCode': 'SA_000000147...
..                                                 ...
500  {'Id': 4539112, 'IndicatorCode': 'SA_000000147...
501  {'Id': 4539183, 'IndicatorCode': 'SA_000000147...
502  {'Id': 4529193, 'IndicatorCode': 'SA_000000147...
503  {'Id': 4539558, 'IndicatorCode': 'SA_000000147...
504  {'Id': 4539491, 'IndicatorCode': 'SA_000000147...

[505 rows x 2 columns]

DataFrame 'df_0' has been written to 'df_0.csv' CSV file.

DataFrame: df_1
                                        @odata.context  \
0    https://ghoapi.azureedge.net/api/$metadata#SA_...
1    https://ghoapi.azureedge.net/api/$metadata#SA_...
2    https://ghoapi.azureedge.net/api/$metadata#SA_...
3    https://ghoapi.azureedge.net/api/$metadata#SA_...
4    https://ghoapi.azureedge.net/api/$metadata#SA_...
..                                                 ...
771  https://ghoapi.azureedge.net/api/$metadata#SA_...
772  https://ghoapi.azureedge.net/api/$metadata#SA_...
773  https://ghoapi.azureedge.net/api/$metadata#SA_...
774  https://ghoapi.azureedge.net/api/$metadata#SA_...
775  https://ghoapi.azureedge.net/api/$metadata#SA_...

                                                 value
0    {'Id': 3148831, 'IndicatorCode': 'SA_000000139...
1    {'Id': 3228489, 'IndicatorCode': 'SA_000000139...
2    {'Id': 3228333, 'IndicatorCode': 'SA_000000139...
3    {'Id': 3228495, 'IndicatorCode': 'SA_000000139...
4    {'Id': 3228382, 'IndicatorCode': 'SA_000000139...
..                                                 ...
771  {'Id': 3148830, 'IndicatorCode': 'SA_000000139...
772  {'Id': 3228305, 'IndicatorCode': 'SA_000000139...
773  {'Id': 3187281, 'IndicatorCode': 'SA_000000139...
774  {'Id': 3148684, 'IndicatorCode': 'SA_000000139...
775  {'Id': 3148630, 'IndicatorCode': 'SA_000000139...

[776 rows x 2 columns]

DataFrame 'df_1' has been written to 'df_1.csv' CSV file.

DataFrame: df_2
                                       @odata.context  \
0   https://ghoapi.azureedge.net/api/$metadata#SA_...
1   https://ghoapi.azureedge.net/api/$metadata#SA_...
2   https://ghoapi.azureedge.net/api/$metadata#SA_...
3   https://ghoapi.azureedge.net/api/$metadata#SA_...
4   https://ghoapi.azureedge.net/api/$metadata#SA_...
5   https://ghoapi.azureedge.net/api/$metadata#SA_...
6   https://ghoapi.azureedge.net/api/$metadata#SA_...
7   https://ghoapi.azureedge.net/api/$metadata#SA_...
8   https://ghoapi.azureedge.net/api/$metadata#SA_...
9   https://ghoapi.azureedge.net/api/$metadata#SA_...
10  https://ghoapi.azureedge.net/api/$metadata#SA_...
11  https://ghoapi.azureedge.net/api/$metadata#SA_...
12  https://ghoapi.azureedge.net/api/$metadata#SA_...
13  https://ghoapi.azureedge.net/api/$metadata#SA_...
14  https://ghoapi.azureedge.net/api/$metadata#SA_...
15  https://ghoapi.azureedge.net/api/$metadata#SA_...
16  https://ghoapi.azureedge.net/api/$metadata#SA_...
17  https://ghoapi.azureedge.net/api/$metadata#SA_...
18  https://ghoapi.azureedge.net/api/$metadata#SA_...
19  https://ghoapi.azureedge.net/api/$metadata#SA_...
20  https://ghoapi.azureedge.net/api/$metadata#SA_...
21  https://ghoapi.azureedge.net/api/$metadata#SA_...
22  https://ghoapi.azureedge.net/api/$metadata#SA_...
23  https://ghoapi.azureedge.net/api/$metadata#SA_...
24  https://ghoapi.azureedge.net/api/$metadata#SA_...
25  https://ghoapi.azureedge.net/api/$metadata#SA_...
26  https://ghoapi.azureedge.net/api/$metadata#SA_...
27  https://ghoapi.azureedge.net/api/$metadata#SA_...
28  https://ghoapi.azureedge.net/api/$metadata#SA_...
29  https://ghoapi.azureedge.net/api/$metadata#SA_...
30  https://ghoapi.azureedge.net/api/$metadata#SA_...
31  https://ghoapi.azureedge.net/api/$metadata#SA_...
32  https://ghoapi.azureedge.net/api/$metadata#SA_...
33  https://ghoapi.azureedge.net/api/$metadata#SA_...
34  https://ghoapi.azureedge.net/api/$metadata#SA_...
35  https://ghoapi.azureedge.net/api/$metadata#SA_...
36  https://ghoapi.azureedge.net/api/$metadata#SA_...
37  https://ghoapi.azureedge.net/api/$metadata#SA_...
38  https://ghoapi.azureedge.net/api/$metadata#SA_...
39  https://ghoapi.azureedge.net/api/$metadata#SA_...
40  https://ghoapi.azureedge.net/api/$metadata#SA_...
41  https://ghoapi.azureedge.net/api/$metadata#SA_...
42  https://ghoapi.azureedge.net/api/$metadata#SA_...
43  https://ghoapi.azureedge.net/api/$metadata#SA_...
44  https://ghoapi.azureedge.net/api/$metadata#SA_...
45  https://ghoapi.azureedge.net/api/$metadata#SA_...
46  https://ghoapi.azureedge.net/api/$metadata#SA_...
47  https://ghoapi.azureedge.net/api/$metadata#SA_...
48  https://ghoapi.azureedge.net/api/$metadata#SA_...
49  https://ghoapi.azureedge.net/api/$metadata#SA_...
50  https://ghoapi.azureedge.net/api/$metadata#SA_...
51  https://ghoapi.azureedge.net/api/$metadata#SA_...
52  https://ghoapi.azureedge.net/api/$metadata#SA_...

                                                value
0   {'Id': 6801917, 'IndicatorCode': 'SA_000000173...
1   {'Id': 6801938, 'IndicatorCode': 'SA_000000173...
2   {'Id': 6801943, 'IndicatorCode': 'SA_000000173...
3   {'Id': 6801912, 'IndicatorCode': 'SA_000000173...
4   {'Id': 6801939, 'IndicatorCode': 'SA_000000173...
5   {'Id': 6801952, 'IndicatorCode': 'SA_000000173...
6   {'Id': 6801951, 'IndicatorCode': 'SA_000000173...
7   {'Id': 6801914, 'IndicatorCode': 'SA_000000173...
8   {'Id': 6801913, 'IndicatorCode': 'SA_000000173...
9   {'Id': 6801911, 'IndicatorCode': 'SA_000000173...
10  {'Id': 6801906, 'IndicatorCode': 'SA_000000173...
11  {'Id': 6801941, 'IndicatorCode': 'SA_000000173...
12  {'Id': 6801929, 'IndicatorCode': 'SA_000000173...
13  {'Id': 6801946, 'IndicatorCode': 'SA_000000173...
14  {'Id': 6801934, 'IndicatorCode': 'SA_000000173...
15  {'Id': 6801933, 'IndicatorCode': 'SA_000000173...
16  {'Id': 6801924, 'IndicatorCode': 'SA_000000173...
17  {'Id': 6801925, 'IndicatorCode': 'SA_000000173...
18  {'Id': 6801902, 'IndicatorCode': 'SA_000000173...
19  {'Id': 6801916, 'IndicatorCode': 'SA_000000173...
20  {'Id': 6801953, 'IndicatorCode': 'SA_000000173...
21  {'Id': 6801927, 'IndicatorCode': 'SA_000000173...
22  {'Id': 6801910, 'IndicatorCode': 'SA_000000173...
23  {'Id': 6801950, 'IndicatorCode': 'SA_000000173...
24  {'Id': 6801909, 'IndicatorCode': 'SA_000000173...
25  {'Id': 6801908, 'IndicatorCode': 'SA_000000173...
26  {'Id': 6801948, 'IndicatorCode': 'SA_000000173...
27  {'Id': 6801928, 'IndicatorCode': 'SA_000000173...
28  {'Id': 6801930, 'IndicatorCode': 'SA_000000173...
29  {'Id': 6801923, 'IndicatorCode': 'SA_000000173...
30  {'Id': 6801936, 'IndicatorCode': 'SA_000000173...
31  {'Id': 6801922, 'IndicatorCode': 'SA_000000173...
32  {'Id': 6801904, 'IndicatorCode': 'SA_000000173...
33  {'Id': 6801944, 'IndicatorCode': 'SA_000000173...
34  {'Id': 6801920, 'IndicatorCode': 'SA_000000173...
35  {'Id': 6801918, 'IndicatorCode': 'SA_000000173...
36  {'Id': 6801907, 'IndicatorCode': 'SA_000000173...
37  {'Id': 6801931, 'IndicatorCode': 'SA_000000173...
38  {'Id': 6801937, 'IndicatorCode': 'SA_000000173...
39  {'Id': 6801921, 'IndicatorCode': 'SA_000000173...
40  {'Id': 6801905, 'IndicatorCode': 'SA_000000173...
41  {'Id': 6801915, 'IndicatorCode': 'SA_000000173...
42  {'Id': 6801926, 'IndicatorCode': 'SA_000000173...
43  {'Id': 6801954, 'IndicatorCode': 'SA_000000173...
44  {'Id': 6801949, 'IndicatorCode': 'SA_000000173...
45  {'Id': 6801919, 'IndicatorCode': 'SA_000000173...
46  {'Id': 6801932, 'IndicatorCode': 'SA_000000173...
47  {'Id': 6801940, 'IndicatorCode': 'SA_000000173...
48  {'Id': 6801935, 'IndicatorCode': 'SA_000000173...
49  {'Id': 6801945, 'IndicatorCode': 'SA_000000173...
50  {'Id': 6801903, 'IndicatorCode': 'SA_000000173...
51  {'Id': 6801942, 'IndicatorCode': 'SA_000000173...
52  {'Id': 6801947, 'IndicatorCode': 'SA_000000173...

DataFrame 'df_2' has been written to 'df_2.csv' CSV file.

DataFrame: df_3
                                        @odata.context  \
0    https://ghoapi.azureedge.net/api/$metadata#SA_...
1    https://ghoapi.azureedge.net/api/$metadata#SA_...
2    https://ghoapi.azureedge.net/api/$metadata#SA_...
3    https://ghoapi.azureedge.net/api/$metadata#SA_...
4    https://ghoapi.azureedge.net/api/$metadata#SA_...
..                                                 ...
752  https://ghoapi.azureedge.net/api/$metadata#SA_...
753  https://ghoapi.azureedge.net/api/$metadata#SA_...
754  https://ghoapi.azureedge.net/api/$metadata#SA_...
755  https://ghoapi.azureedge.net/api/$metadata#SA_...
756  https://ghoapi.azureedge.net/api/$metadata#SA_...

                                                 value
0    {'Id': 4909442, 'IndicatorCode': 'SA_000000152...
1    {'Id': 4890030, 'IndicatorCode': 'SA_000000152...
2    {'Id': 4890050, 'IndicatorCode': 'SA_000000152...
3    {'Id': 4880303, 'IndicatorCode': 'SA_000000152...
4    {'Id': 4898785, 'IndicatorCode': 'SA_000000152...
..                                                 ...
752  {'Id': 4898895, 'IndicatorCode': 'SA_000000152...
753  {'Id': 4909460, 'IndicatorCode': 'SA_000000152...
754  {'Id': 4899006, 'IndicatorCode': 'SA_000000152...
755  {'Id': 4898952, 'IndicatorCode': 'SA_000000152...
756  {'Id': 4890085, 'IndicatorCode': 'SA_000000152...

[757 rows x 2 columns]

DataFrame 'df_3' has been written to 'df_3.csv' CSV file.

DataFrame: df_4
                                         @odata.context  \
0     https://ghoapi.azureedge.net/api/$metadata#WHO...
1     https://ghoapi.azureedge.net/api/$metadata#WHO...
2     https://ghoapi.azureedge.net/api/$metadata#WHO...
3     https://ghoapi.azureedge.net/api/$metadata#WHO...
4     https://ghoapi.azureedge.net/api/$metadata#WHO...
...                                                 ...
2323  https://ghoapi.azureedge.net/api/$metadata#WHO...
2324  https://ghoapi.azureedge.net/api/$metadata#WHO...
2325  https://ghoapi.azureedge.net/api/$metadata#WHO...
2326  https://ghoapi.azureedge.net/api/$metadata#WHO...
2327  https://ghoapi.azureedge.net/api/$metadata#WHO...

                                                  value
0     {'Id': 5521472, 'IndicatorCode': 'WHOSIS_00000...
1     {'Id': 5389281, 'IndicatorCode': 'WHOSIS_00000...
2     {'Id': 5456131, 'IndicatorCode': 'WHOSIS_00000...
3     {'Id': 5321425, 'IndicatorCode': 'WHOSIS_00000...
4     {'Id': 5521430, 'IndicatorCode': 'WHOSIS_00000...
...                                                 ...
2323  {'Id': 5321452, 'IndicatorCode': 'WHOSIS_00000...
2324  {'Id': 5456525, 'IndicatorCode': 'WHOSIS_00000...
2325  {'Id': 5456498, 'IndicatorCode': 'WHOSIS_00000...
2326  {'Id': 5321445, 'IndicatorCode': 'WHOSIS_00000...
2327  {'Id': 5322815, 'IndicatorCode': 'WHOSIS_00000...

[2328 rows x 2 columns]

DataFrame 'df_4' has been written to 'df_4.csv' CSV file.

In [5]:
display(df_0)

,@odata.context,value
0,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4548508, 'IndicatorCode': 'SA_000000147..."
1,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539127, 'IndicatorCode': 'SA_000000147..."
2,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539079, 'IndicatorCode': 'SA_000000147..."
3,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539550, 'IndicatorCode': 'SA_000000147..."
4,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4519729, 'IndicatorCode': 'SA_000000147..."
...,...,...
500,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539112, 'IndicatorCode': 'SA_000000147..."
501,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539183, 'IndicatorCode': 'SA_000000147..."
502,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4529193, 'IndicatorCode': 'SA_000000147..."
503,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539558, 'IndicatorCode': 'SA_000000147..."
504,https://ghoapi.azureedge.net/api/$metadata#SA_...,"{'Id': 4539491, 'IndicatorCode': 'SA_000000147..."

In [7]:
# Drop the first column from df_0
df_0.drop(df_0.columns[0], axis=1, inplace=True)

display(df_0)
# # Extract 'Id' from the dictionary in the ' @odata.context' column and replace it
# df_0['@odata.context'] = df_0['@odata.context'].apply(pd.Series)['Id']

# # Display the modified DataFrame
# print(df_0)

                                                 value
0    {'Id': 4548508, 'IndicatorCode': 'SA_000000147...
1    {'Id': 4539127, 'IndicatorCode': 'SA_000000147...
2    {'Id': 4539079, 'IndicatorCode': 'SA_000000147...
3    {'Id': 4539550, 'IndicatorCode': 'SA_000000147...
4    {'Id': 4519729, 'IndicatorCode': 'SA_000000147...
..                                                 ...
500  {'Id': 4539112, 'IndicatorCode': 'SA_000000147...
501  {'Id': 4539183, 'IndicatorCode': 'SA_000000147...
502  {'Id': 4529193, 'IndicatorCode': 'SA_000000147...
503  {'Id': 4539558, 'IndicatorCode': 'SA_000000147...
504  {'Id': 4539491, 'IndicatorCode': 'SA_000000147...

[505 rows x 1 columns]

In [9]:
expanded_df = pd.json_normalize(df_0['value'])
display(expanded_df)

,Id,IndicatorCode,SpatialDimType,SpatialDim,ParentLocationCode,TimeDimType,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE_SA_0000001476_HUN,3,3.0,None,None,None,2018-10-25T13:07:08+02:00,2013,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
1,4539127,SA_0000001476,COUNTRY,CAN,AMR,YEAR,Americas,None,None,2004,...,DATASOURCE_SA_0000001476_CAN,2.1,2.1,None,None,None,2018-10-25T13:07:00+02:00,2004,2004-01-01T00:00:00+01:00,2004-12-31T00:00:00+01:00
2,4539079,SA_0000001476,COUNTRY,GBR,EUR,YEAR,Europe,None,None,2012,...,DATASOURCE_SA_0000001476_GBR,1.6,1.6,None,None,None,2018-10-25T13:07:01+02:00,2012,2012-01-01T00:00:00+01:00,2012-12-31T00:00:00+01:00
3,4539550,SA_0000001476,COUNTRY,NOR,EUR,YEAR,Europe,None,None,1995,...,DATASOURCE_SA_0000001476_NOR,4.1,4.1,None,None,None,2018-10-25T13:07:03+02:00,1995,1995-01-01T00:00:00+01:00,1995-12-31T00:00:00+01:00
4,4519729,SA_0000001476,COUNTRY,MDA,EUR,YEAR,Europe,None,None,1992,...,DATASOURCE_SA_0000001476_MDA,2.2,2.2,None,None,None,2018-10-25T13:07:09+02:00,1992,1992-01-01T00:00:00+01:00,1992-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,4539112,SA_0000001476,COUNTRY,AUT,EUR,YEAR,Europe,None,None,2000,...,DATASOURCE_SA_0000001476_AUT,1.4,1.4,None,None,None,2018-10-25T13:07:03+02:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
501,4539183,SA_0000001476,COUNTRY,ROU,EUR,YEAR,Europe,None,None,2008,...,DATASOURCE_SA_0000001476_ROU,4,4.0,None,None,None,2018-10-25T13:07:11+02:00,2008,2008-01-01T00:00:00+01:00,2008-12-31T00:00:00+01:00
502,4529193,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2002,...,DATASOURCE_SA_0000001476_FIN,5.5,5.5,None,None,None,2018-10-25T13:07:09+02:00,2002,2002-01-01T00:00:00+01:00,2002-12-31T00:00:00+01:00
503,4539558,SA_0000001476,COUNTRY,DNK,EUR,YEAR,Europe,None,None,1999,...,DATASOURCE_SA_0000001476_DNK,2.3,2.3,None,None,None,2018-10-25T13:07:11+02:00,1999,1999-01-01T00:00:00+01:00,1999-12-31T00:00:00+01:00
504,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE_SA_0000001476_FIN,4.2,4.2,None,None,None,2018-10-25T13:07:04+02:00,2014,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00