In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import requests
import json
import csv

In [2]:
#define data to pull from WHO GHO API
url= "https://ghoapi.azureedge.net/api/SA_0000001476"
url1= "https://ghoapi.azureedge.net/api/SA_0000001398"
url2= "https://ghoapi.azureedge.net/api/SA_0000001732"
url3= "https://ghoapi.azureedge.net/api/SA_0000001523"
url4= "https://ghoapi.azureedge.net/api/WHOSIS_000002"
url5= "https://ghoapi.azureedge.net/api/SA_0000001822"
url6= "https://ghoapi.azureedge.net/api/SA_0000001398"
url7= "https://ghoapi.azureedge.net/api/TAXBEV_MOSTSOLDSPIRIT"
url8= "https://ghoapi.azureedge.net/api/SA_0000001400_ARCHIVED"
url9= "https://ghoapi.azureedge.net/api/SA_0000001688"
url10= "https://ghoapi.azureedge.net/api/SA_0000001398_ARCHIVED"


# list to store URLS 
urls= [url,url1,url2,url3,url4,url5,url6,url7,url8, url9, url10]

# Dictionary to store dataframes
dataframes = {}

In [3]:
# Fetch data from each URL and create dataframes
for idx, url in enumerate(urls):
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        df_name = f"df_{idx}"  # Name the dataframe
        dataframes[df_name] = pd.DataFrame(data)
        print("Data from", url, "has been fetched and stored in", df_name)
    else:
        print("Failed to fetch data from", url)

Data from https://ghoapi.azureedge.net/api/SA_0000001476 has been fetched and stored in df_0
Data from https://ghoapi.azureedge.net/api/SA_0000001398 has been fetched and stored in df_1
Data from https://ghoapi.azureedge.net/api/SA_0000001732 has been fetched and stored in df_2
Data from https://ghoapi.azureedge.net/api/SA_0000001523 has been fetched and stored in df_3
Data from https://ghoapi.azureedge.net/api/WHOSIS_000002 has been fetched and stored in df_4
Data from https://ghoapi.azureedge.net/api/SA_0000001822 has been fetched and stored in df_5
Data from https://ghoapi.azureedge.net/api/SA_0000001398 has been fetched and stored in df_6
Data from https://ghoapi.azureedge.net/api/TAXBEV_MOSTSOLDSPIRIT has been fetched and stored in df_7
Data from https://ghoapi.azureedge.net/api/SA_0000001400_ARCHIVED has been fetched and stored in df_8
Data from https://ghoapi.azureedge.net/api/SA_0000001688 has been fetched and stored in df_9
Data from https://ghoapi.azureedge.net/api/SA_0000001398_ARCHIVED has been fetched and stored in df_10

In [4]:
# Assuming dataframes is a dictionary containing DataFrames
# Assuming dataframes is a dictionary containing DataFrames
for df_name, df in dataframes.items():
    # Expand dictionaries into separate columns and rows
    expanded_df = pd.json_normalize(df['value'])  # Replace 'your_column_name_here' with the actual column name
    
    # Assign the expanded DataFrame back to the original variable
    globals()[df_name] = expanded_df
    
    # Print the DataFrame
    print("DataFrame:", df_name)
    print(expanded_df)
    print()

    # Write DataFrame to CSV
    csv_filename = f"{df_name}.csv"
    expanded_df.to_csv(csv_filename, index=False)
    print(f"DataFrame '{df_name}' has been written to '{csv_filename}' CSV file.")
    print()


# # Create variables for each DataFrame
# for df_name, df in dataframes.items():
#     globals()[df_name] = df

# # Test the created dataframes and write each dataframe to CSV
# for df_name, df in dataframes.items():
#     print("DataFrame:", df_name)
#     print(df)
#     print()


# # Write dataframe to CSV
#     csv_filename = f"{df_name}.csv"
#     df.to_csv(csv_filename, index=False)
#     print(f"DataFrame '{df_name}' has been written to '{csv_filename}' CSV file.")
#     print()

DataFrame: df_0
          Id  IndicatorCode SpatialDimType SpatialDim ParentLocationCode  \
0    4548508  SA_0000001476        COUNTRY        HUN                EUR
1    4539127  SA_0000001476        COUNTRY        CAN                AMR
2    4539550  SA_0000001476        COUNTRY        NOR                EUR
3    4519729  SA_0000001476        COUNTRY        MDA                EUR
4    4529155  SA_0000001476        COUNTRY        NOR                EUR
..       ...            ...            ...        ...                ...
500  4539514  SA_0000001476        COUNTRY        ESP                EUR
501  4539109  SA_0000001476        COUNTRY        CAN                AMR
502  4548503  SA_0000001476        COUNTRY        MKD                EUR
503  4529154  SA_0000001476        COUNTRY        ISL                EUR
504  4539491  SA_0000001476        COUNTRY        FIN                EUR

    TimeDimType ParentLocation Dim1Type  Dim1  TimeDim  ...  \
0          YEAR         Europe     None  None     2013  ...
1          YEAR       Americas     None  None     2004  ...
2          YEAR         Europe     None  None     1995  ...
3          YEAR         Europe     None  None     1992  ...
4          YEAR         Europe     None  None     2001  ...
..          ...            ...      ...   ...      ...  ...
500        YEAR         Europe     None  None     1992  ...
501        YEAR       Americas     None  None     1999  ...
502        YEAR         Europe     None  None     2012  ...
503        YEAR         Europe     None  None     2001  ...
504        YEAR         Europe     None  None     2014  ...

                    DataSourceDim Value NumericValue   Low  High Comments  \
0    DATASOURCE_SA_0000001476_HUN     3          3.0  None  None     None
1    DATASOURCE_SA_0000001476_CAN   2.1          2.1  None  None     None
2    DATASOURCE_SA_0000001476_NOR   4.1          4.1  None  None     None
3    DATASOURCE_SA_0000001476_MDA   2.2          2.2  None  None     None
4    DATASOURCE_SA_0000001476_NOR   3.9          3.9  None  None     None
..                            ...   ...          ...   ...   ...      ...
500  DATASOURCE_SA_0000001476_ESP   1.3          1.3  None  None     None
501  DATASOURCE_SA_0000001476_CAN     2          2.0  None  None     None
502  DATASOURCE_SA_0000001476_MKD   1.8          1.8  None  None     None
503  DATASOURCE_SA_0000001476_ISL   3.5          3.5  None  None     None
504  DATASOURCE_SA_0000001476_FIN   4.2          4.2  None  None     None

                          Date  TimeDimensionValue         TimeDimensionBegin  \
0    2018-10-25T13:07:08+02:00                2013  2013-01-01T00:00:00+01:00
1    2018-10-25T13:07:00+02:00                2004  2004-01-01T00:00:00+01:00
2    2018-10-25T13:07:03+02:00                1995  1995-01-01T00:00:00+01:00
3    2018-10-25T13:07:09+02:00                1992  1992-01-01T00:00:00+01:00
4    2018-10-25T13:07:05+02:00                2001  2001-01-01T00:00:00+01:00
..                         ...                 ...                        ...
500  2018-10-25T13:07:10+02:00                1992  1992-01-01T00:00:00+01:00
501  2018-10-25T13:07:10+02:00                1999  1999-01-01T00:00:00+01:00
502  2018-10-25T13:07:08+02:00                2012  2012-01-01T00:00:00+01:00
503  2018-10-25T13:07:00+02:00                2001  2001-01-01T00:00:00+01:00
504  2018-10-25T13:07:04+02:00                2014  2014-01-01T00:00:00+01:00

              TimeDimensionEnd
0    2013-12-31T00:00:00+01:00
1    2004-12-31T00:00:00+01:00
2    1995-12-31T00:00:00+01:00
3    1992-12-31T00:00:00+01:00
4    2001-12-31T00:00:00+01:00
..                         ...
500  1992-12-31T00:00:00+01:00
501  1999-12-31T00:00:00+01:00
502  2012-12-31T00:00:00+01:00
503  2001-12-31T00:00:00+01:00
504  2014-12-31T00:00:00+01:00

[505 rows x 25 columns]

DataFrame 'df_0' has been written to 'df_0.csv' CSV file.

DataFrame: df_1
          Id  IndicatorCode SpatialDimType SpatialDim ParentLocationCode  \
0    3148831  SA_0000001398        COUNTRY        GEO                EUR
1    3228489  SA_0000001398        COUNTRY        WSM                WPR
2    3228495  SA_0000001398        COUNTRY        YEM                EMR
3    3148774  SA_0000001398        COUNTRY        DOM                AMR
4    3148629  SA_0000001398        COUNTRY        BEN                AFR
..       ...            ...            ...        ...                ...
771  3187247  SA_0000001398        COUNTRY        KOR                WPR
772  3148644  SA_0000001398        COUNTRY        BHR                EMR
773  3148785  SA_0000001398        COUNTRY        EGY                EMR
774  3187316  SA_0000001398        COUNTRY        MEX                AMR
775  3228305  SA_0000001398        COUNTRY        PRT                EUR

    TimeDimType         ParentLocation     Dim1Type  TimeDim  \
0          YEAR                 Europe  ALCOHOLTYPE     2016
1          YEAR        Western Pacific  ALCOHOLTYPE     2016
2          YEAR  Eastern Mediterranean  ALCOHOLTYPE     2016
3          YEAR               Americas  ALCOHOLTYPE     2016
4          YEAR                 Africa  ALCOHOLTYPE     2016
..          ...                    ...          ...      ...
771        YEAR        Western Pacific  ALCOHOLTYPE     2016
772        YEAR  Eastern Mediterranean  ALCOHOLTYPE     2016
773        YEAR  Eastern Mediterranean  ALCOHOLTYPE     2016
774        YEAR               Americas  ALCOHOLTYPE     2016
775        YEAR                 Europe  ALCOHOLTYPE     2016

                             Dim1  ... DataSourceDim Value NumericValue   Low  \
0             ALCOHOLTYPE_SA_WINE  ...          None    43         None  None
1    ALCOHOLTYPE_SA_OTHER_ALCOHOL  ...          None     0         None  None
2             ALCOHOLTYPE_SA_WINE  ...          None     0         None  None
3          ALCOHOLTYPE_SA_SPIRITS  ...          None  41.9         None  None
4    ALCOHOLTYPE_SA_OTHER_ALCOHOL  ...          None  13.6         None  None
..                            ...  ...           ...   ...          ...   ...
771        ALCOHOLTYPE_SA_SPIRITS  ...          None   7.1         None  None
772           ALCOHOLTYPE_SA_BEER  ...          None    19         None  None
773  ALCOHOLTYPE_SA_OTHER_ALCOHOL  ...          None   0.6         None  None
774           ALCOHOLTYPE_SA_WINE  ...          None   2.1         None  None
775  ALCOHOLTYPE_SA_OTHER_ALCOHOL  ...          None   4.7         None  None

     High Comments                       Date TimeDimensionValue  \
0    None     None  2018-09-21T08:24:00+02:00               2016
1    None     None  2018-09-21T08:24:16+02:00               2016
2    None     None  2018-09-21T08:24:05+02:00               2016
3    None     None  2018-09-21T08:24:09+02:00               2016
4    None     None  2018-09-21T08:24:02+02:00               2016
..    ...      ...                        ...                ...
771  None     None  2018-09-21T08:24:14+02:00               2016
772  None     None  2018-09-21T08:24:00+02:00               2016
773  None     None  2018-09-21T08:24:07+02:00               2016
774  None     None  2018-09-21T08:24:13+02:00               2016
775  None     None  2018-09-21T08:24:11+02:00               2016

            TimeDimensionBegin           TimeDimensionEnd
0    2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
1    2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
2    2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
3    2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
4    2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
..                         ...                        ...
771  2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
772  2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
773  2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
774  2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00
775  2016-01-01T00:00:00+01:00  2016-12-31T00:00:00+01:00

[776 rows x 25 columns]

DataFrame 'df_1' has been written to 'df_1.csv' CSV file.

DataFrame: df_2
         Id  IndicatorCode SpatialDimType SpatialDim TimeDimType  \
0   6801917  SA_0000001732        COUNTRY        EST        YEAR
1   6801938  SA_0000001732        COUNTRY        MNE        YEAR
2   6801912  SA_0000001732        COUNTRY        CYP        YEAR
3   6801951  SA_0000001732        COUNTRY        TKM        YEAR
4   6801914  SA_0000001732        COUNTRY        DEU        YEAR
5   6801911  SA_0000001732        COUNTRY        CHE        YEAR
6   6801906  SA_0000001732        COUNTRY        AZE        YEAR
7   6801929  SA_0000001732        COUNTRY        KAZ        YEAR
8   6801946  SA_0000001732        COUNTRY        SRB        YEAR
9   6801925  SA_0000001732        COUNTRY        IRL        YEAR
10  6801902  SA_0000001732        COUNTRY        ALB        YEAR
11  6801953  SA_0000001732        COUNTRY        UKR        YEAR
12  6801927  SA_0000001732        COUNTRY        ISR        YEAR
13  6801910  SA_0000001732        COUNTRY        BLR        YEAR
14  6801909  SA_0000001732        COUNTRY        BIH        YEAR
15  6801908  SA_0000001732        COUNTRY        BGR        YEAR
16  6801948  SA_0000001732        COUNTRY        SVN        YEAR
17  6801928  SA_0000001732        COUNTRY        ITA        YEAR
18  6801923  SA_0000001732        COUNTRY        HRV        YEAR
19  6801936  SA_0000001732        COUNTRY        MKD        YEAR
20  6801922  SA_0000001732        COUNTRY        GRC        YEAR
21  6801904  SA_0000001732        COUNTRY        ARM        YEAR
22  6801920  SA_0000001732        COUNTRY        GBR        YEAR
23  6801918  SA_0000001732        COUNTRY        FIN        YEAR
24  6801919  SA_0000001732        COUNTRY        FRA        YEAR
25  6801932  SA_0000001732        COUNTRY        LUX        YEAR
26  6801940  SA_0000001732        COUNTRY        NOR        YEAR
27  6801903  SA_0000001732        COUNTRY        AND        YEAR
28  6801937  SA_0000001732        COUNTRY        MLT        YEAR
29  6801931  SA_0000001732        COUNTRY        LTU        YEAR
30  6801907  SA_0000001732        COUNTRY        BEL        YEAR
31  6801944  SA_0000001732        COUNTRY        RUS        YEAR
32  6801930  SA_0000001732        COUNTRY        KGZ        YEAR
33  6801950  SA_0000001732        COUNTRY        TJK        YEAR
34  6801916  SA_0000001732        COUNTRY        ESP        YEAR
35  6801924  SA_0000001732        COUNTRY        HUN        YEAR
36  6801933  SA_0000001732        COUNTRY        LVA        YEAR
37  6801934  SA_0000001732        COUNTRY        MCO        YEAR
38  6801941  SA_0000001732        COUNTRY        POL        YEAR
39  6801913  SA_0000001732        COUNTRY        CZE        YEAR
40  6801952  SA_0000001732        COUNTRY        TUR        YEAR
41  6801939  SA_0000001732        COUNTRY        NLD        YEAR
42  6801943  SA_0000001732        COUNTRY        ROU        YEAR
43  6801947  SA_0000001732        COUNTRY        SVK        YEAR
44  6801942  SA_0000001732        COUNTRY        PRT        YEAR
45  6801945  SA_0000001732        COUNTRY        SMR        YEAR
46  6801935  SA_0000001732        COUNTRY        MDA        YEAR
47  6801949  SA_0000001732        COUNTRY        SWE        YEAR
48  6801954  SA_0000001732        COUNTRY        UZB        YEAR
49  6801926  SA_0000001732        COUNTRY        ISL        YEAR
50  6801915  SA_0000001732        COUNTRY        DNK        YEAR
51  6801905  SA_0000001732        COUNTRY        AUT        YEAR
52  6801921  SA_0000001732        COUNTRY        GEO        YEAR

   ParentLocationCode ParentLocation Dim1Type  Dim1  TimeDim  ...  \
0                 EUR         Europe     None  None     2012  ...
1                 EUR         Europe     None  None     2012  ...
2                 EUR         Europe     None  None     2012  ...
3                 EUR         Europe     None  None     2012  ...
4                 EUR         Europe     None  None     2012  ...
5                 EUR         Europe     None  None     2012  ...
6                 EUR         Europe     None  None     2012  ...
7                 EUR         Europe     None  None     2012  ...
8                 EUR         Europe     None  None     2012  ...
9                 EUR         Europe     None  None     2012  ...
10                EUR         Europe     None  None     2012  ...
11                EUR         Europe     None  None     2012  ...
12                EUR         Europe     None  None     2012  ...
13                EUR         Europe     None  None     2012  ...
14                EUR         Europe     None  None     2012  ...
15                EUR         Europe     None  None     2012  ...
16                EUR         Europe     None  None     2012  ...
17                EUR         Europe     None  None     2012  ...
18                EUR         Europe     None  None     2012  ...
19                EUR         Europe     None  None     2012  ...
20                EUR         Europe     None  None     2012  ...
21                EUR         Europe     None  None     2012  ...
22                EUR         Europe     None  None     2012  ...
23                EUR         Europe     None  None     2012  ...
24                EUR         Europe     None  None     2012  ...
25                EUR         Europe     None  None     2012  ...
26                EUR         Europe     None  None     2012  ...
27                EUR         Europe     None  None     2012  ...
28                EUR         Europe     None  None     2012  ...
29                EUR         Europe     None  None     2012  ...
30                EUR         Europe     None  None     2012  ...
31                EUR         Europe     None  None     2012  ...
32                EUR         Europe     None  None     2012  ...
33                EUR         Europe     None  None     2012  ...
34                EUR         Europe     None  None     2012  ...
35                EUR         Europe     None  None     2012  ...
36                EUR         Europe     None  None     2012  ...
37                EUR         Europe     None  None     2012  ...
38                EUR         Europe     None  None     2012  ...
39                EUR         Europe     None  None     2012  ...
40                EUR         Europe     None  None     2012  ...
41                EUR         Europe     None  None     2012  ...
42                EUR         Europe     None  None     2012  ...
43                EUR         Europe     None  None     2012  ...
44                EUR         Europe     None  None     2012  ...
45                EUR         Europe     None  None     2012  ...
46                EUR         Europe     None  None     2012  ...
47                EUR         Europe     None  None     2012  ...
48                EUR         Europe     None  None     2012  ...
49                EUR         Europe     None  None     2012  ...
50                EUR         Europe     None  None     2012  ...
51                EUR         Europe     None  None     2012  ...
52                EUR         Europe     None  None     2012  ...

   DataSourceDim Value NumericValue   Low  High      Comments  \
0           None   Yes         None  None  None          None
1           None    No         None  None  None          None
2           None    No         None  None  None          None
3           None  None         None  None  None  missing data
4           None   Yes         None  None  None          None
5           None    No         None  None  None          None
6           None    No         None  None  None          None
7           None  None         None  None  None  missing data
8           None    No         None  None  None          None
9           None    No         None  None  None          None
10          None   Yes         None  None  None          None
11          None   Yes         None  None  None          None
12          None  None         None  None  None  missing data
13          None   Yes         None  None  None          None
14          None    No         None  None  None          None
15          None   Yes         None  None  None          None
16          None   Yes         None  None  None          None
17          None   Yes         None  None  None          None
18          None   Yes         None  None  None          None
19          None    No         None  None  None          None
20          None   Yes         None  None  None          None
21          None   Yes         None  None  None          None
22          None   Yes         None  None  None          None
23          None   Yes         None  None  None          None
24          None    No         None  None  None          None
25          None   Yes         None  None  None          None
26          None   Yes         None  None  None          None
27          None  None         None  None  None  missing data
28          None    No         None  None  None          None
29          None   Yes         None  None  None          None
30          None    No         None  None  None          None
31          None   Yes         None  None  None          None
32          None   Yes         None  None  None          None
33          None  None         None  None  None  missing data
34          None   Yes         None  None  None          None
35          None   Yes         None  None  None          None
36          None   Yes         None  None  None          None
37          None  None         None  None  None  missing data
38          None   Yes         None  None  None          None
39          None   Yes         None  None  None          None
40          None    No         None  None  None          None
41          None    No         None  None  None          None
42          None   Yes         None  None  None          None
43          None    No         None  None  None          None
44          None   Yes         None  None  None          None
45          None   Yes         None  None  None          None
46          None   Yes         None  None  None          None
47          None   Yes         None  None  None          None
48          None  None         None  None  None  missing data
49          None   Yes         None  None  None          None
50          None   Yes         None  None  None          None
51          None    No         None  None  None          None
52          None  None         None  None  None  missing data

                         Date TimeDimensionValue         TimeDimensionBegin  \
0   2014-01-03T16:09:30+01:00               2012  2012-01-01T00:00:00+01:00
1   2014-01-03T16:09:31+01:00               2012  2012-01-01T00:00:00+01:00
2   2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
3   2014-01-14T14:45:57+01:00               2012  2012-01-01T00:00:00+01:00
4   2014-01-03T16:09:30+01:00               2012  2012-01-01T00:00:00+01:00
5   2014-01-03T16:09:32+01:00               2012  2012-01-01T00:00:00+01:00
6   2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
7   2014-01-14T14:45:57+01:00               2012  2012-01-01T00:00:00+01:00
8   2014-01-03T16:09:31+01:00               2012  2012-01-01T00:00:00+01:00
9   2014-01-03T16:09:30+01:00               2012  2012-01-01T00:00:00+01:00
10  2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
11  2014-01-03T16:09:32+01:00               2012  2012-01-01T00:00:00+01:00
12  2014-01-14T14:45:57+01:00               2012  2012-01-01T00:00:00+01:00
13  2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
14  2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
15  2014-01-03T16:09:29+01:00               2012  2012-01-01T00:00:00+01:00
16  2014-01-03T16:09:32+01:00               2012  2012-01-01T00:00:00+01:00
17  2014-01-03T16:09:30+01:00               2012  2012-01-01T00:00:00+01:00

In [5]:
display(df_0)

,Id,IndicatorCode,SpatialDimType,SpatialDim,ParentLocationCode,TimeDimType,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE_SA_0000001476_HUN,3,3.0,None,None,None,2018-10-25T13:07:08+02:00,2013,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
1,4539127,SA_0000001476,COUNTRY,CAN,AMR,YEAR,Americas,None,None,2004,...,DATASOURCE_SA_0000001476_CAN,2.1,2.1,None,None,None,2018-10-25T13:07:00+02:00,2004,2004-01-01T00:00:00+01:00,2004-12-31T00:00:00+01:00
2,4539550,SA_0000001476,COUNTRY,NOR,EUR,YEAR,Europe,None,None,1995,...,DATASOURCE_SA_0000001476_NOR,4.1,4.1,None,None,None,2018-10-25T13:07:03+02:00,1995,1995-01-01T00:00:00+01:00,1995-12-31T00:00:00+01:00
3,4519729,SA_0000001476,COUNTRY,MDA,EUR,YEAR,Europe,None,None,1992,...,DATASOURCE_SA_0000001476_MDA,2.2,2.2,None,None,None,2018-10-25T13:07:09+02:00,1992,1992-01-01T00:00:00+01:00,1992-12-31T00:00:00+01:00
4,4529155,SA_0000001476,COUNTRY,NOR,EUR,YEAR,Europe,None,None,2001,...,DATASOURCE_SA_0000001476_NOR,3.9,3.9,None,None,None,2018-10-25T13:07:05+02:00,2001,2001-01-01T00:00:00+01:00,2001-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,4539514,SA_0000001476,COUNTRY,ESP,EUR,YEAR,Europe,None,None,1992,...,DATASOURCE_SA_0000001476_ESP,1.3,1.3,None,None,None,2018-10-25T13:07:10+02:00,1992,1992-01-01T00:00:00+01:00,1992-12-31T00:00:00+01:00
501,4539109,SA_0000001476,COUNTRY,CAN,AMR,YEAR,Americas,None,None,1999,...,DATASOURCE_SA_0000001476_CAN,2,2.0,None,None,None,2018-10-25T13:07:10+02:00,1999,1999-01-01T00:00:00+01:00,1999-12-31T00:00:00+01:00
502,4548503,SA_0000001476,COUNTRY,MKD,EUR,YEAR,Europe,None,None,2012,...,DATASOURCE_SA_0000001476_MKD,1.8,1.8,None,None,None,2018-10-25T13:07:08+02:00,2012,2012-01-01T00:00:00+01:00,2012-12-31T00:00:00+01:00
503,4529154,SA_0000001476,COUNTRY,ISL,EUR,YEAR,Europe,None,None,2001,...,DATASOURCE_SA_0000001476_ISL,3.5,3.5,None,None,None,2018-10-25T13:07:00+02:00,2001,2001-01-01T00:00:00+01:00,2001-12-31T00:00:00+01:00
504,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE_SA_0000001476_FIN,4.2,4.2,None,None,None,2018-10-25T13:07:04+02:00,2014,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00

In [6]:
# # Drop the first column from df_0
# df_0.drop(df_0.columns[0], axis=1, inplace=True)

# display(df_0)
# # # Extract 'Id' from the dictionary in the ' @odata.context' column and replace it
# # df_0['@odata.context'] = df_0['@odata.context'].apply(pd.Series)['Id']

# # # Display the modified DataFrame
# # print(df_0)

In [7]:
# expanded_df = pd.json_normalize(df_0['value'])
# display(expanded_df)

In [8]:
df_0_4= pd.merge(df_0, df_4, on=['TimeDimensionValue', 'SpatialDim'], how='inner')
display(df_0_4)

,Id_x,IndicatorCode_x,SpatialDimType_x,SpatialDim,ParentLocationCode_x,TimeDimType_x,ParentLocation_x,Dim1Type_x,Dim1_x,TimeDim_x,...,DataSourceDimType_y,DataSourceDim_y,Value_y,NumericValue_y,Low_y,High_y,Comments_y,Date_y,TimeDimensionBegin_y,TimeDimensionEnd_y
0,4539116,SA_0000001476,COUNTRY,GRC,EUR,YEAR,Europe,None,None,2000,...,None,None,68.6,68.63454,None,None,None,2020-12-04T17:01:17+01:00,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
1,4539116,SA_0000001476,COUNTRY,GRC,EUR,YEAR,Europe,None,None,2000,...,None,None,69.8,69.81720,None,None,None,2020-12-04T17:01:16+01:00,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
2,4539116,SA_0000001476,COUNTRY,GRC,EUR,YEAR,Europe,None,None,2000,...,None,None,67.5,67.46355,None,None,None,2020-12-04T17:01:16+01:00,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
3,4548491,SA_0000001476,COUNTRY,ROU,EUR,YEAR,Europe,None,None,2010,...,None,None,68.1,68.11747,None,None,None,2020-12-04T17:02:58+01:00,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
4,4548491,SA_0000001476,COUNTRY,ROU,EUR,YEAR,Europe,None,None,2010,...,None,None,62.8,62.81327,None,None,None,2020-12-04T17:02:58+01:00,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,4548522,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2015,...,None,None,68.7,68.67419,None,None,None,2020-12-04T17:01:26+01:00,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
182,4548522,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2015,...,None,None,64.3,64.34644,None,None,None,2020-12-04T17:01:26+01:00,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
183,4539194,SA_0000001476,COUNTRY,DNK,EUR,YEAR,Europe,None,None,2010,...,None,None,68.8,68.77981,None,None,None,2020-12-04T17:00:46+01:00,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
184,4539194,SA_0000001476,COUNTRY,DNK,EUR,YEAR,Europe,None,None,2010,...,None,None,69.4,69.41515,None,None,None,2020-12-04T17:00:47+01:00,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
185,4539194,SA_0000001476,COUNTRY,DNK,EUR,YEAR,Europe,None,None,2010,...,None,None,70.0,70.02374,None,None,None,2020-12-04T17:00:46+01:00,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00

In [9]:
# Write DataFrame to CSV
df_0_4.to_csv("life_expectancy_household_percent.csv", index=False)

In [20]:
percap_household_exp = pd.merge(df_0, df_8, on=['TimeDimensionValue', 'SpatialDim'], how='inner')

# Display the resulting merged dataframe
display(percap_household_exp)
percap_household_exp.to_csv("percap_household_exp.csv", index=False)

,Id_x,IndicatorCode_x,SpatialDimType_x,SpatialDim,ParentLocationCode_x,TimeDimType_x,ParentLocation_x,Dim1Type_x,Dim1_x,TimeDim_x,...,DataSourceDimType_y,DataSourceDim_y,Value_y,NumericValue_y,Low_y,High_y,Comments_y,Date_y,TimeDimensionBegin_y,TimeDimensionEnd_y
0,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE,DATASOURCE_GISAHHUN,3.79,3.79,None,None,None,2018-04-20T12:52:42+02:00,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
1,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE,DATASOURCE_GISAHHUN,0,0.00,None,None,None,2020-05-27T10:18:09+02:00,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
2,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE,DATASOURCE_GISAHHUN,0.00,0.00,None,None,None,2018-04-20T12:42:17+02:00,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
3,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE,DATASOURCE_GISAHHUN,3.2,3.20,None,None,None,2020-05-27T10:18:09+02:00,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
4,4548508,SA_0000001476,COUNTRY,HUN,EUR,YEAR,Europe,None,None,2013,...,DATASOURCE,DATASOURCE_GISAHHUN,3.35,3.35,None,None,None,2018-04-20T12:42:36+02:00,2013-01-01T00:00:00+01:00,2013-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE,DATASOURCE_GISAHFIN,8.80,8.80,None,None,None,2018-04-20T12:56:55+02:00,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00
3879,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE,DATASOURCE_GISAHFIN,0.97,0.97,None,None,None,2018-04-20T12:55:25+02:00,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00
3880,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE,DATASOURCE_GISAHFIN,4.17,4.17,None,None,None,2020-05-27T10:17:38+02:00,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00
3881,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE,DATASOURCE_GISAHFIN,1.67,1.67,None,None,None,2018-04-20T12:45:41+02:00,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00
3882,4539491,SA_0000001476,COUNTRY,FIN,EUR,YEAR,Europe,None,None,2014,...,DATASOURCE,DATASOURCE_GISAHFIN,1.8,1.80,None,None,None,2020-05-27T10:17:38+02:00,2014-01-01T00:00:00+01:00,2014-12-31T00:00:00+01:00

In [ ]:
#3 and 7 are a mess-- due to multiple country codes due to diff alc types
# maindf = pd.merge(maindf, df_3, on=['TimeDimensionValue', 'SpatialDim'], how='inner')maindf = pd.merge(maindf, df_5, on=['TimeDimensionValue', 'SpatialDim'], how='inner')
# maindf = pd.merge(maindf, df_7, on=['TimeDimensionValue', 'SpatialDim'], how='inner')